### ISSUE TITLE
Tabs don't show on iOS 10.2

### ISSUE THREAD

**Issue by ujellyx** [Bensge/FullSafari#3]
Unfortunately doesn't work on the newest iOS 10.2. The tabs just won't show.

**Comment by Bensge** [comment]
It's working just fine on my phone on 10.2. Did you try the latest version?

**Comment by Bensge** [comment]
I found some issues on iOS 10 after using the tweak for a while. Rotation handling is completely broken and needs fixing

**Comment by Bensge** [comment]
Should be working now. The latest build is available on bensge.com/fullsafaribeta
